apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-mcp-jwt-credentials
  namespace: wasmcloud-system
spec:
  refreshInterval: 10s
  updatePolicy: Replace
  deletionPolicy: Delete
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    secret:
      name: mcp-jwt-credentials-writable
  data:
    - match:
        remoteRef:
          remoteKey: wash/mcp-jwt-credentials-rotated
